spring:
  application:
    name: event-management-service
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: https://eureka-registry-service.apps.reunite.ga/eureka/
welcome:
  message : Spring One Demo